ALTER TABLE tags
	ADD COLUMN tag_type VARCHAR(255) NOT NULL DEFAULT 'DEFAULT',
	ADD COLUMN it_system_uuid VARCHAR(36) NULL;

ALTER TABLE tags_aud
	ADD COLUMN tag_type VARCHAR(255) NULL,
	ADD COLUMN it_system_uuid VARCHAR(36) NULL;
