ALTER TABLE persons ADD COLUMN dead BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE persons_aud ADD COLUMN dead BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE persons ADD COLUMN disenfranchised BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE persons_aud ADD COLUMN disenfranchised BOOLEAN NOT NULL DEFAULT FALSE;