server.port=9020

# Various development settings
environment.dev=true
spring.thymeleaf.cache=false
spring.messages.cacheSeconds=1
spring.output.ansi.enabled=always

# Allow classes to autowire themselves
spring.main.allow-circular-references=true

# SQL settings for development
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sofd?useSSL=false&serverTimezone=Europe/Copenhagen&characterEncoding=utf8&sessionVariables=sql_mode=''
spring.datasource.username=root
spring.datasource.password=Test1234

# SAML settings for development
di.saml.sp.entityId=https://localhost:9020
di.saml.sp.baseUrl=https://localhost:9020
di.saml.idp.metadataLocation=url:https://demo-adfs.digital-identity.dk/FederationMetadata/2007-06/FederationMetadata.xml
di.saml.keystore.location=config/security/samlKeystore.pfx
di.saml.keystore.password=Test1234

# SSL settings for development
server.ssl.key-store=classpath:ssl-demo.pfx
server.ssl.key-store-password=Test1234
server.ssl.key-password=Test1234
server.ssl-key-store-type=pkcs12

# SQL Debugging
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type.descriptor.sql=trace
spring.datasource.hikari.leak-detection-threshold=180000

# Fixed production settings
server.tomcat.remote_ip_header=x-forwarded-for
server.tomcat.protocol_header=x-forwarded-proto
management.context-path=/manage


# Application settings
sofd.scheduled.enabled=true
sofd.scheduled.modificationHistoryCleanup.days=10
sofd.scheduled.addressSync.enabled=false
sofd.scheduled.addressSync.runOnStartup=false
sofd.scheduled.accountOrderGeneration.masters=OPUS,SOFD,ActiveDirectory
sofd.scheduled.childrenSync.enabled=false
sofd.scheduled.childrenSync.runOnStartup=false
sofd.scheduled.deleteOldAffiliations.enabled=false
sofd.scheduled.deleteOldAffiliations.days=90

sofd.actuator.username=admin
sofd.actuator.password=Test1234

sofd.modules.chart.enabled=true
sofd.modules.localLogin.enabled=false
sofd.modules.los.enabled=true
sofd.modules.los.altOrgsEnabled=true
sofd.modules.los.futureOrgsEnabled=true
sofd.modules.telephony.enabled=false
sofd.modules.profile.enabled=true
sofd.modules.contactPlaces.enabled=true
sofd.modules.accountCreation.enabled=true
sofd.modules.accountCreation.accountOrderApprove=true
sofd.modules.accountCreation.reuseExistingUsernames=false
sofd.modules.accountCreation.opusHandler.enabled=false
sofd.modules.accountCreation.opusHandler.defaultEmail=
sofd.modules.accountCreation.opusHandler.municipalityNumber=
sofd.modules.accountCreation.opusHandler.keystore=
sofd.modules.accountCreation.opusHandler.keystorePwd=
sofd.modules.accountCreation.opusHandler.wsUrl=
sofd.modules.smsGateway.enabled=true
sofd.modules.smsGateway.smsEnabled=true
sofd.modules.smsGateway.pwdReminderEnabled=true
sofd.modules.smsGateway.url=http://localhost:5000/
sofd.modules.personComments.enabled=true
#sofd.modules.historial-reports-on-orgunits.enabled=true
sofd.modules.functionHierarchy.enabled=true
#sofd.modules.manager.editEnabled=true
sofd.modules.positionDisplayName.enabled=true
sofd.modules.person.chosenNameEditable=true
sofd.modules.substitute.enabled=true
sofd.modules.orgUnitSubstitute.enabled=true
sofd.modules.affiliation.alternativeOUAssignable=true
sofd.modules.managerUI.managerUISubstituteContextIdentifier=MANAGER_UI

#S3 settings
sofd.s3.region=eu-west-1
sofd.s3.AWSAccessKeyId=
sofd.s3.AWSSecretAccessKey=
sofd.s3.BucketName=
sofd.s3.HistoricalReportsPath=

sofd.integrations.eboks.enabled=false
sofd.integrations.eboks.url=
sofd.integrations.eboks.materialeId=
sofd.integrations.eboks.senderId=
#sofd.integrations.kle.url=
sofd.integrations.opus.enableFiltering=true
sofd.integrations.opus.enableLosIdMatch=true
sofd.integrations.opus.enableAutoAffiliationConfiguration=true
sofd.integrations.opus.enableActiveDirectoryEmployeeIdAssociation=true
sofd.integrations.opus.adEmployeeIdAssociationLimitedToPrimeAffiliation=false
sofd.integrations.opus.positionIds=17,40,99
sofd.integrations.opus.losIds=80,90,100
sofd.integrations.opus.orgUnitInfix=(nedlagt
sofd.integrations.cpr.url=https://localhost:8808/
sofd.integrations.children.url=http://localhost:8080/children
sofd.integrations.children.affiliationMasters=OPUS
sofd.integrations.os2sync.enabled=false
sofd.integrations.os2sync.cprEnabled=false
sofd.integrations.os2sync.datasourceUrl=jdbc:mysql://localhost:3306/os2sync?useSSL=false
sofd.integrations.os2sync.datasourceUsername=root
sofd.integrations.os2sync.datasourcePassword=Test1234
sofd.integrations.os2sync.restUrl=http://192.168.50.181:5000/api/hierarchy
sofd.integrations.roleCatalogue.apiKey=Test1234
sofd.integrations.roleCatalogue.url=https://localhost:8090/api
sofd.integrations.email.enabled=false
sofd.integrations.email.username=
sofd.integrations.email.password=
sofd.integrations.email.host=
sofd.integrations.appManager.url=https://appmanager.digital-identity.dk/api
#sofd.integrations.cvr.enabled=true
#sofd.integrations.cvr.apiKey=
sofd.customer.cvr=29189978

sofd.emailTemplate.domainFilterEnabled=true
sofd.emailTemplate.orgFilterEnabled=true
sofd.emailTemplate.adUserFilterEnabled=true

sofd.hidePersonAddresses=true
sofd.showOpusFunctionsOnPersonPage=false

#cron.historicalreportsonorgunits.task=0 * * * * ?
#cron.notification.task=0 * * * * ?
#cron.account.generation=0 0/2 * * * ?
